### ISSUE TITLE
Create User not working

### ISSUE THREAD

**Issue by AhmedThahir** [sakshamssr/Stock-Market-Simulator#2]
Going to `http://localhost:8000/createuser` redirects me to `http://localhost:8000/login`

**Comment by sakshamssr** [comment]
Correct url for signup page is http://localhost:8000/signup

**Comment by AhmedThahir** [comment]
I can see that you've fixed it in https://github.com/sakshamssr/Investa/commit/ba732e237aa9e24dcd7341a0a23a9651432b37e3
